include(GNUInstallDirs)

install(
	DIRECTORY ${CMAKE_SOURCE_DIR}/src/carl/
	DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/carl
	FILES_MATCHING REGEX ".*\.(h|tpp)$"
)

install(
	TARGETS carl-shared carl-static
	EXPORT carlTargets
	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
	ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

install(FILES ${CMAKE_BINARY_DIR}/carlConfig.install.cmake DESTINATION ${CMAKE_INSTALL_DIR} RENAME carlConfig.cmake)
install(FILES ${CMAKE_BINARY_DIR}/carlConfigVersion.cmake DESTINATION ${CMAKE_INSTALL_DIR})
install(EXPORT carlTargets FILE carlTargets.cmake DESTINATION ${CMAKE_INSTALL_DIR})
