option(ENABLE_PACKAGING "Use CPack for packaging." OFF)

if(ENABLE_PACKAGING)
	set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
	set(CPACK_PACKAGE_VENDOR "RWTH Aachen University")

	set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
	set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
	set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

	set(CPACK_DEBIAN_PACKAGE_DEBUG "ON")

	set(CPACK_SOURCE_GENERATOR "DEB")
	set(CPACK_GENERATOR "DEB")

	set(CPACK_SOURCE_IGNORE_FILES "/build/")

	# DEB
	set(CPACK_DEBIAN_PACKAGE_NAME "libcarl")
	set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgmp10, libgmp-dev, libeigen3-dev, libboost-all-dev")
	set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Gereon Kremer <gereon.kremer@cs.rwth-aachen.de>")
	set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${PROJECT_DESCRIPTION}")
	set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/ths-rwth/carl")

	include(CPack)
endif()
